version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    groups:
      all-actions:
        patterns: [ "*" ]
