version: 2
registries:
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: ChildMindInstituteCNL
    password: ${{ secrets.GHCR_REGISTRY_TOKEN }}
updates:
  - package-ecosystem: "github-actions"
    directory: /
    # Check for updates once a week
    schedule:
      interval: weekly
    groups:
      all-actions:
        patterns: [ "*" ]
    target-branch: develop
    registries:
    - ghcr
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    groups:
      production dependencies:
        dependency-type: production
      development dependencies:
        dependency-type: development
    target-branch: develop
    registries:
    - ghcr
