#!/usr/bin/env python3
import os
import sys
from traceback import print_exc

def replace_primary_repo(yaml_string, local_owner):
    return yaml_string.replace('ghcr.io/fcp-indi', f'ghcr.io/{local_owner}')

if __name__ == '__main__':
    if len(sys.argv) != 3:
        raise SyntaxError('Usage: local_ghcr $FILE $OWNER')
    file, owner = sys.argv[1:]
    dockerfiles = '.github/Dockerfiles'
    new_Dockerfile = replace_primary_repo(
        open(file, 'r').read(),
        owner
    )
    open(file, 'w').write(new_Dockerfile)
