body:
- attributes:
    value: "Please check [open issues](https://github.com/FCP-INDI/C-PAC/issues) before\
      \ adding a new bug report. If something like your bug is already reported, please\
      \ add to that discussion. Also, please change \"[User-reported Bug]\" in the\
      \ title of this issue to something more descriptive of the bug you are reporting.\
      \ If you'd like to update the emoji, consider checking [Gitm\U0001F602ji](https://gitmoji.dev)\
      \ for guidance on emoji selection. Clicking an emoji image on that page will\
      \ copy it to your clipboard."
  type: markdown
- attributes:
    description: A clear and concise description of what the bug is.
    label: Describe the bug
    placeholder: Tell us what you see!
  id: description
  type: textarea
  validations:
    required: true
- attributes:
    description: Steps to reproduce the behavior.
    label: To reproduce
    placeholder: '1. Go to ''...''

      2. Click on ''....''

      3. Scroll down to ''....''

      4. See error

      '
  id: reproduction
  type: textarea
  validations:
    required: false
- attributes:
    description: Preconfigured pipeline, if using a preconfigured pipeline. Otherwise,
      please provide your custom pipeline configuration below.
    label: Preconfig
    options:
    - label: default
    - label: abcd-options
    - label: abcd-prep
    - label: anat-only
    - label: benchmark-FNIRT
    - label: ccs-options
    - label: fmriprep-ingress
    - label: fmriprep-options
    - label: fx-options
    - label: monkey
    - label: ndmg
    - label: nhp-macaque
    - label: preproc
    - label: rbc-options
    - label: rodent
  id: preconfig
  type: checkboxes
- attributes:
    description: Custom pipeline configuration, if using a custom pipeline configuration
      (you can paste the text here or upload the file as plain text or as a `.zip`).
      Otherwise, please select the relevant preconfigured pipeline(s) above.
    label: Custom pipeline configuration
    placeholder: '```YML

      FROM: default

      ```

      '
  id: custom_config
  type: textarea
  validations:
    required: false
- attributes:
    description: The terminal command used to start the problematic run.
    label: Run command
    placeholder: '```BASH

      cpac run $BIDS_DIR $OUTPUT_DIR participant

      ```

      '
  id: runcommand
  type: textarea
  validations:
    required: false
- attributes:
    description: A clear and concise description of what you expected to happen.
    label: Expected behavior
    placeholder: Tell us what you thought you'd see!
  id: expectation
  type: textarea
  validations:
    required: true
- attributes:
    description: What needs to be true for this issue to be considered resolved?
    label: Acceptance criteria
    placeholder: "Tell us what you'd like to see!\n- [ ] criterion 1\n- [ ] criterion\
      \ 2\n\u2026\n"
  id: criteria
  type: textarea
  validations:
    required: true
- attributes:
    description: If applicable, add screenshots to help explain your problem.
    label: Screenshots
    placeholder: Show us what you see!
  id: screenshots
  type: textarea
  validations:
    required: false
- attributes:
    label: C-PAC version
    placeholder: v1.8.7
  id: c-pac-version
  type: input
  validations:
    required: false
- attributes:
    description: As many as are relevant
    label: Container platform
    multiple: true
    options:
    - Apptainer
    - Docker
    - Singularity
  id: container-platform
  type: dropdown
  validations:
    required: false
- attributes:
    label: Container platfomr version(s)
    placeholder: Apptainer Apptainer v1.3.4; Docker v27.2.0; Singularity v4.2
  id: container-platform-version
  type: input
  validations:
    required: false
- attributes:
    description: Add any other context about the problem here.
    label: Additional context
  id: additional
  type: textarea
  validations:
    required: false
description: Create a report to help us improve
labels:
- bug
- user-reported
name: Bug report
title: "\U0001F41B [User-reported Bug]"
