def enum(**enums):
    return type('Enum', (), enums)


control = enum(CHOICE_BOX = 0, 
               TEXT_BOX = 1, 
               COMBO_BOX = 2,
               INT_CTRL = 3,
               FLOAT_CTRL = 4,
               DIR_COMBO_BOX = 5,
               CHECKLIST_BOX = 6,
               LISTBOX_COMBO = 7,
               TEXTBOX_COMBO = 8,
               CHECKBOX_GRID = 9)

dtype = enum(BOOL = 0,
             STR= 1,
             NUM= 2,
             LBOOL = 3,
             LSTR = 4,
             LNUM = 5,
             LOFL = 6,
             COMBO = 7,
             LDICT= 8 ) 


substitution_map = {'On': 1,
                    'Off': 0,
                    'On/Off': 10,
                    'ANTS & FSL': 11,
                    '3dAutoMask & BET': 12,
                    'ALFF':'alff_to_standard',
                    'ALFF_z':'alff_to_standard_zstd',
                    'ALFF (smoothed)':'alff_to_standard_smooth',
                    'ALFF (smoothed)_z':'alff_to_standard_smooth_zstd',
                    'f/ALFF':'falff_to_standard',
                    'f/ALFF_z':'falff_to_standard_zstd',
                    'f/ALFF (smoothed)':'falff_to_standard_smooth',
                    'f/ALFF (smoothed)_z':'falff_to_standard_smooth_zstd',
                    'ReHo':'reho_to_standard',
                    'ReHo_z':'reho_to_standard_zstd',
                    'ReHo (smoothed)':'reho_to_standard_smooth',
                    'ReHo (smoothed)_z':'reho_to_standard_smooth_zstd',
                    'ROI Average SCA':'sca_roi_files_to_standard',
                    'ROI Average SCA_z':'sca_roi_files_to_standard_fisher_zstd',
                    'ROI Average SCA (smoothed)':'sca_roi_files_to_standard_smooth',
                    'ROI Average SCA (smoothed)_z':'sca_roi_files_to_standard_smooth_fisher_zstd',
                    'Voxelwise SCA':'sca_seed_to_standard',
                    'Voxelwise SCA_z':'sca_seed_to_standard_fisher_zstd',
                    'Voxelwise SCA (smoothed)':'sca_seed_to_standard_smooth',
                    'Voxelwise SCA (smoothed)_z': 'sca_seed_to_standard_smooth_fisher_zstd',
                    'Multiple Regression SCA':'sca_tempreg_maps_files',
                    'Multiple Regression SCA (smoothed)':'sca_tempreg_maps_files_smooth',
                    'Multiple Regression SCA_z':'sca_tempreg_maps_zstat_files',
                    'Multiple Regression SCA (smoothed)_z':'sca_tempreg_maps_zstat_files_smooth',
                    'VMHC (z-score std only)_z':'vmhc_fisher_zstd',
                    'VMHC z-stat (z-score std only)_z':'vmhc_fisher_zstd_zstat_map',
                    'Network Centrality':'centrality_outputs',
                    'Network Centrality_z':'centrality_outputs_zstd',
                    'Network Centrality (smoothed)':'centrality_outputs_smoothed',
                    'Network Centrality (smoothed)_z': 'centrality_outputs_smoothed_zstd',
                    'Dual Regression':'dr_tempreg_maps_files_to_standard',
                    'Dual Regression (smoothed)':'dr_tempreg_maps_files_to_standard_smooth',
                    'Dual Regression_z':'dr_tempreg_maps_zstat_files_to_standard',
                    'Dual Regression (smoothed)_z':'dr_tempreg_maps_zstat_files_to_standard_smooth',
                    'End': 'None',
                    'ROI Average Time Series Extraction': 'roi_average',
                    'ROI Voxelwise Time Series Extraction': 'roi_voxelwise',
                   }


multiple_value_wfs = ['runAnatomicalPreprocessing',
                      'runFunctionalPreprocessing',
                      'runRegistrationPreprocessing',
                      'runRegisterFuncToMNI',
                      'runAnatomicalToFunctionalRegistration',
                      'runSegmentationPreprocessing',
                      'runNuisance',
                      'runFrequencyFiltering',
                      'runMedianAngleCorrection',
                      'runGenerateMotionStatistics',
                      'runScrubbing',
                      'runFristonModel']
