# Import packages
import os
import sys
import re
import commands
import nipype.pipeline.engine as pe
import nipype.interfaces.utility as util


def compute_fisher_z_score(correlation_file, timeseries_one_d):

    """
    Computes the fisher z transform of the input correlation map
    If the correlation map contains data for multiple ROIs then 
    the function returns z score for each ROI as a seperate nifti 
    file


    Parameters
    ----------
    correlation_file: string
        Input correlations file

    Returns
    -------
    out_file : list (nifti files)
        list of z_scores for mask or ROI
    """

    import nibabel as nb
    import numpy as np
    import os

    roi_numbers = []
    if '#' in open(timeseries_one_d, 'r').readline().rstrip('\r\n'):
        roi_numbers = open(timeseries_one_d, 'r').readline().rstrip('\r\n').replace('#', '').split('\t')

    corr_img = nb.load(correlation_file)
    corr_data = corr_img.get_data()

    hdr = corr_img.get_header()

    corr_data = np.log((1 + corr_data) / (1 - corr_data)) / 2.0

    dims = corr_data.shape

    out_file = []

    if len(dims) == 5 or len(roi_numbers) > 0:

        if len(dims) == 5:
            x, y, z, one, roi_number = dims

            corr_data = np.reshape(corr_data, (x * y * z, roi_number), order='F')


        for i in range(0, len(roi_numbers)):

            sub_data = corr_data
            if len(dims) == 5:
                sub_data = np.reshape(corr_data[:, i], (x, y, z), order='F')

            sub_img = nb.Nifti1Image(sub_data, header=corr_img.get_header(), affine=corr_img.get_affine())

            sub_z_score_file = os.path.join(os.getcwd(), 'z_score_ROI_number_%s.nii.gz' % (roi_numbers[i]))

            sub_img.to_filename(sub_z_score_file)

            out_file.append(sub_z_score_file)

    else:

        z_score_img = nb.Nifti1Image(corr_data, header=hdr, affine=corr_img.get_affine())

        z_score_file = os.path.join(os.getcwd(), 'z_score.nii.gz')

        z_score_img.to_filename(z_score_file)

        out_file.append(z_score_file)


    return out_file

def check_ts(in_file):
    import numpy as np
    try:
        timepoints, rois = np.loadtxt(in_file).shape
    except ValueError:
        timepoints = np.loadtxt(in_file).shape[0]
        rois = 1	
    if rois > timepoints:
        message = ('\n\n\n****The number of timepoints (' + str(timepoints)
                   + ') is smaller than the number of ROIs to run ('
                   + str(rois) + ') - therefore the GLM is'
                   + ' underspecified and can\'t run.****\n\n\n')
        print(message)
        raise Exception(message)
    else:
        return in_file


def map_to_roi(timeseries, maps):
    """
    Renames the outputs of the temporal multiple regression workflow for sca 
    according to the header information of the timeseries.txt file that was 
    passed
    
    NOTE: This is only run if the temporal regression is run as part of sca
          (which = 'RT') when calling the temporal regression workflow.
          If you run the temporal regression workflow manually, don\'t set 
          (which = 'RT') unless you provide a timeseries.txt file with a header
          containing the names of the timeseries


    Parameters
    ----------

    timeseries: string
        Input timeseries.txt file
        
    maps: List (nifti files)
        List of output files generated by the temporal regression workflow if
        (which == 'RT')
    

    Returns
    -------

    labels : List (strings)
        List of names that the output files should be renamed to
        
    maps: List (nifti files)
        List of output files generated by the temporal regression workflow if
        (which == 'RT')
    """

    try:
        import os
        import numpy as np
        testMat = np.loadtxt(timeseries)
        timepoints, rois = testMat.shape

        if rois > timepoints:
            raise Exception('The number of timepoints is smaller than the'
                            + ' number of ROIs to run - therefore the'
                            + ' GLM is underspecified and can\'t run.')
        labels = open(timeseries, 'r').readline().split()
        
        new_labels = []
        
        for l in labels:
        
            if "#" in l:
                l = l.replace("#","")        
                new_labels.append(os.path.join(os.getcwd(), \
                    'sca_tempreg_z_maps_roi_' + str(l)))
        numMaps = len(maps)
        maps.sort()
        if not numMaps / 2 == rois:
            raise Exception('You specified ' + str(rois) + ' timeseries but '
                            + ' only ' + str(numMaps / 2) + ' spatial maps were'
                            + ' generated')
        maps = maps[:rois]
        # output = zip(labels, component_maps)
        print "labels, maps", new_labels, maps
    except Exception:
        print "Error while mapping roi to dual regression split 3d volumes"
    return new_labels, maps
