name: Build stages

on:
  push:


jobs:
  Ubuntu:
    name: Build C-PAC Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files using defaults
        id: ubuntu-dockerfile-changed
        uses: tj-actions/changed-files@v6.2
        with:
          # regex
          files: |
            \.github/Dockerfiles/Ubuntu.*\.Dockerfile
      
      - name: Set up Docker Buildx
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to GitHub Container Registry
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase tag
        run: |
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/ubuntu:bionic-non-free" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      
      - name: Build and push Docker image
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2.4.0
        with:
          file: .github/Dockerfiles/Ubuntu.bionic-non-free.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_TAG }}
