name: Build and test C-PAC

on:
  workflow_dispatch:

jobs:
  C-PAC:
    uses: shnizzedy/C-PAC/.github/workflows/build_C-PAC.yml@CI/GitHub-workflows # TODO: Set to FCP-INDI/**@main
    with:
      variant: ''

  C-PAC-lite:
    needs: C-PAC
    uses: shnizzedy/C-PAC/.github/workflows/build_C-PAC.yml@CI/GitHub-workflows # TODO: Set to FCP-INDI/**@main
    with:
      variant: lite

  C-PAC-ABCD-HCP:
    uses: shnizzedy/C-PAC/.github/workflows/build_C-PAC.yml@CI/GitHub-workflows # TODO: Set to FCP-INDI/**@main
    with:
      variant: ABCD-HCP

  C-PAC-fMRIPrep-LTS:
    uses: shnizzedy/C-PAC/.github/workflows/build_C-PAC.yml@CI/GitHub-workflows # TODO: Set to FCP-INDI/**@main
    with:
      variant: fMRIPrep-LTS

  Circle_tests:
    name: Run tests on CircleCI
    runs-on: ubuntu-latest
    needs:
      - C-PAC-ABCD-HCP
      - C-PAC-fMRIPrep-LTS
      - C-PAC-lite
    steps:
      - name: Trigger CircleCI workflow
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.2
        env:
          CCI_TOKEN: ${{ secrets.CIRCLE_API_USER_TOKEN }}
