# Requires secret `ACTIONS_WORKFLOW_TOKEN` with `workflow` scope

name: Build stages

on:
  workflow_dispatch:
    inputs:
      base_ref:
        description: 'Base reference if triggered by a pull request'
        required: false
        default: ""


jobs:
  Ubuntu:
    name: Build C-PAC Ubuntu
    strategy:
      matrix:
        Dockerfile: 
        - Ubuntu.bionic-non-free
        - Ubuntu.xenial-20200114
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: |
          TAG=$(sed 's/\./:/' <(echo ${{ matrix.Dockerfile }}))
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
  
  stages:
    name: Build Docker stage images
    needs: Ubuntu
    strategy:
      matrix:
        Dockerfile:
        - AFNI.16.2.07.neurodocker-xenial
        - AFNI.20.0.04-bionic
        - ANTs.2.2.0.neurodocker-bionic
        - c3d.1.0.0-xenial
        - connectome-workbench.1.3.2-1.neurodebian-bionic
        - connectome-workbench.1.3.2-2.neurodebian-xenial
        - FreeSurfer.6.0.0-min.neurodocker-bionic
        - FreeSurfer.6.0.1-min-xenial
        - FSL.5.0.9-5.neurodebian-xenial
        - FSL.5.0.10-bionic
        - ICA-AROMA.0.4.5-xenial
        - msm.2.0-bionic
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        if: github.event.inputs.base_ref != ''
        uses: actions/checkout@v2
      - name: Clear up some space on runner
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: |
          TAG=$(sed 's/\./:/' <(echo ${{ matrix.Dockerfile }}))
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Prep Dockerfiles for forked repository
        if: github.repository_owner != 'FCP-INDI'
        run: |
            .github/scripts/local_ghcr .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile ${{ github.repository_owner }}
            cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
      - name: See Dockerfile
        run: cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-base:
    needs: stages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - standard
          - ABCD-HCP
          - fMRIPrep-LTS
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v4
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - name: Check out C-PAC
      if: github.event.inputs.base_ref != ''
      uses: actions/checkout@v2
    - name: Prep source files
      run: sed -i -e 's/^/\.github\/Dockerfiles\//' .github/stage_requirements/${{ matrix.variant }}.txt
    - name: Clear up some space on runner
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set tag
      run: |
        TAG="stage-base:${{ matrix.variant }}-$(cat version)"
        echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
    - name: Prep Dockerfiles for forked repository
      run: |
          .github/scripts/local_ghcr .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile ${{ github.repository_owner }}
          cat .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
    - name: See Dockerfile
      run: cat .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
    - name: Build and push base image
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        file: .github/Dockerfiles/base-${{ matrix.variant }}.Dockerfile
        push: true
        tags: |
          ${{ env.DOCKER_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  trigger-next-workflow:
    needs: build-base
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Build and test C-PAC
        run: gh workflow run build_and_test.yml --ref ${GITHUB_REF_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
