name: Build stages

on:
  push:
    branches:
      - main
      - develop
      - CI/GitHub-workflows

jobs:
  Ubuntu:
    name: Build C-PAC Ubuntu
    strategy:
      matrix:
        Dockerfile: 
        - Ubuntu.bionic-non-free
        - Ubuntu.xenial-20200114
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files using defaults
        id: ubuntu-dockerfile-changed
        uses: tj-actions/changed-files@v6.2
        with:
          # regex
          files: |
            \.github/Dockerfiles/${{ matrix.Dockerfile }}\.Dockerfile
      - name: Clear up some space on runner
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up Docker Buildx
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: |
          TAG=$(sed 's/\./:/' <(echo ${{ matrix.Dockerfile }}))
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Build and push Docker image
        if: steps.ubuntu-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2.7.0
        with:
          file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_TAG }}
  
  stages:
    name: Build Docker stage images
    needs: Ubuntu
    strategy:
      matrix:
        Dockerfile: 
        - AFNI.20.0.04-bionic
        - AFNI.update.afni.binaries-bionic
        - ANTs.2.3.4.neurodocker-bionic
        - ANTs.2.3.5-bionic
        - c3d.1.0.0-bionic
        - FreeSurfer.6.0.0-min.neurodocker-bionic
        - FSL.neurodebian-bionic
        - ICA-AROMA.0.4.3-beta-bionic
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files using defaults
        id: dockerfile-changed
        uses: tj-actions/changed-files@v6.2
        with:
          # regex
          files: |
            \.github/Dockerfiles/${{ matrix.Dockerfile }}\.Dockerfile
            \.github/workflows/build_stages\.yml
      - name: Clear up some space on runner
        if: steps.dockerfile-changed.outputs.any_changed == 'true'
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Set up Docker Buildx
        if: steps.dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        if: steps.dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set tag
        run: |
          TAG=$(sed 's/\./:/' <(echo ${{ matrix.Dockerfile }}))
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}/$TAG" | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Prep Dockerfiles for forked repository
        if: github.repository_owner != 'FCP-INDI'
        run: |
            .github/scripts/local_ghcr .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile ${{ github.repository_owner }}
            cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
      - name: See Dockerfile
        run: cat .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
      - name: Set up Docker Buildx
        if: steps.dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Container Registry
        if: steps.dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: steps.dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          file: .github/Dockerfiles/${{ matrix.Dockerfile }}.Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_TAG }}

  trigger-next-workflow:
    needs: stages
    runs-on: ubuntu-latest
    steps:
      - name: Build and test C-PAC
        run: gh workflow run "Build and test C-PAC" --ref $(echo ${GITHUB_REF} | cut -d '/' -f 3-)