# Copyright (C) 2022-2023  C-PAC Developers

# This file is part of C-PAC.

# C-PAC is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.

# C-PAC is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
# License for more details.

# You should have received a copy of the GNU Lesser General Public
# License along with C-PAC. If not, see <https://www.gnu.org/licenses/>.
name: Build and test C-PAC

on:
  push:

jobs:
  check-updated-preconfigs:
    name: Check if preconfigs need updated
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v4 
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Check if version updated
        run: |
          git config --global user.email "CMI_CPAC_Support@childmind.org"
          git config --global user.name "Theodore (Machine User)"
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
          export PYTHONPATH=$PWD
          pip install -q wheel
          pip install -q nipype numpy matplotlib pandas pathvalidate pytz pyyaml voluptuous
          python ./CPAC/utils/configuration/yaml_template.py
          if [[ ! -z $(git diff origin/${GITHUB_BRANCH}) ]]
          then
            git add CPAC/resources/configs
            git commit -m ":bulb: Update comments based on default preconfig"
          fi
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          if [[ ! "$COMMIT_MESSAGE" == *"Update version to"* ]]
          then
            cd CPAC
            VERSION=$(python -c "from info import __version__; print('.'.join(('.'.join(__version__[::-1].split('-')[1].split('.')[1:])[::-1], __version__.split('-')[1])) if '-' in __version__ else __version__)")
            cd ..
            echo "v${VERSION}" > version
            find ./CPAC/resources/configs -name "*.yml" -exec sed -i -r "s/^(# [Vv]ersion ).*$/# Version ${VERSION}/g" {} \;
            git add version
            VERSIONS=($(git diff origin/${GITHUB_BRANCH} -- version | tail -n 2))
            export PATTERN="(declare|typeset) -a"
            if [[ "$(declare -p VERSIONS)" =~ $PATTERN ]]
            then
              for DOCKERFILE in $(find ./.github/Dockerfiles -name "*.Dockerfile")
              do
                export IFS=""
                for LINE in $(grep "FROM ghcr\.io/fcp\-indi/c\-pac/.*\-${VERSIONS[0]:1}" ${DOCKERFILE})
                do
                  echo "Updating stage tags in ${DOCKERFILE}"
                  sed -i "s/\-${VERSIONS[0]:1}/\-${VERSIONS[1]:1}/g" ${DOCKERFILE}
                done
              done
              unset IFS
            fi
            if [[ ! -z $(git diff origin/${GITHUB_BRANCH}) ]]
            then
              git add CPAC/resources/configs .github/Dockerfiles
              git commit -m ":bookmark: Update version to ${VERSION} ($COMMIT_MESSAGE)" || true
              git push origin HEAD:${GITHUB_BRANCH} || true
            fi
            cd ..
          fi
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]
          then
            cd $HOME/work/C-PAC/C-PAC
            for DOCKERFILE in $(ls .github/Dockerfiles/C-PAC.develop-*.Dockerfile)
            do
              if [[ "$DOCKERFILE" =~ .*C-PAC.develop-(.*)-(bionic|xenial).Dockerfile ]]
              then
                cp $DOCKERFILE variant-${BASH_REMATCH[1]}.Dockerfile
              else
                cp $DOCKERFILE Dockerfile
              fi
            done
            git add *ockerfile
            git commit -m ":truck: Copy develop Dockerfiles to root directory \
            \
            [skip ci]"
            git push origin HEAD:${GITHUB_BRANCH} || true
          fi

  get_branch_ref:
    if: github.ref_type == 'branch'
    name: Get base SHAs for open PRs
    needs: check-updated-preconfigs
    outputs:
      base_refs:
        ${{ steps.base_refs.outputs.base_refs }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: base_refs
        name: Gather base_refs
        run: |
          pip install PyGithub
          BASE_REFS=$(python ${GITHUB_WORKSPACE}/.github/scripts/get_pr_base_shas.py)
          if [ -n "$BASE_REFS" ]
          then
            echo "base_refs=$(jq --compact-output --null-input '$ARGS.positional' --args -- $BASE_REFS)" >> $GITHUB_OUTPUT
          else
            echo "base_refs=$(jq --compact-output --null-input '$ARGS.positional' --args -- '')" >> $GITHUB_OUTPUT
          fi
          cat $GITHUB_OUTPUT

  build-stages_branch:
    name: Build multistage image stages
    needs: get_branch_ref
    strategy:
      matrix:
        base_ref: ${{ fromJSON(needs.get_branch_ref.outputs.base_refs) }}
    uses: ./.github/workflows/build_stages.yml
    with:
      base_ref: ${{ strategy.matrix.base_ref }}

  build-stages_tag:
    if: github.ref_type == 'tag'
    name: Build multistage image stages
    needs: check-updated-preconfigs
    uses: ./.github/workflows/build_stages.yml
