name: Test participant preconfigurations

on:
  workflow_call:
    inputs:
      variant:
        required: true
        type: string
      preconfig:
        required: true
        type: string
      subject:
        required: true
        type: string

jobs:
  test_config:
    