name: Run Regression Lite Test


on:
  #pull_request:
  #  types: [ready_for_review]
  push:
    branches: regression/after-runs
  workflow_call:
    secrets:
      GH_CLI_BIN_PATH:
        description: 'path to directory containing GitHub CLI binary if not on default $PATH'
        required: false
      SSH_PRIVATE_KEY:
        required: true
      SSH_USER:
        required: true
      SSH_HOST:
        required: true
      SSH_WORK_DIR:
        required: true

jobs: 
  test:
    name: Regression Test - Lite
    environment: ACCESS
    runs-on: ubuntu-latest
    steps: 
      - name: Get C-PAC branch
        run: |
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
          if [[ ! $GITHUB_BRANCH == 'main' ]] && [[ ! $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=${GITHUB_BRANCH//\//_}
          elif [[ $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=nightly
          elif [[ $GITHUB_BRANCH == 'main' ]]
          then
            TAG=latest
          fi
          TAG=$TAG$VARIANT
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):$TAG >> $GITHUB_ENV
          cat $GITHUB_ENV

      #- name: Checkout Code
      #  uses: actions/checkout@v2
      #- name: Clone slurm_testing
      #  run: |
      #    git clone https://github.com/cmi-dair/slurm_testing

      - name: Install SSH Keys
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H -t rsa ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Connect and Run Regression Test Lite
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 200m
          script: |
            cd ${{ secrets.SSH_WORK_DIR }}
            if [ ! -d slurm_testing_callback ] ; then
                git clone https://github.com/shnizzedy/slurm_testing slurm_testing_callback
            else
                cd slurm_testing_callback
                git pull origin regression/after_runs
                cd ..
            fi
            mkdir -p ./logs/${{ github.sha }}
            if [ -z "${{ secrets.GH_CLI_BIN_PATH }}" ]
            then
              sbatch -N 1 -p RM-shared -t 00:05:00 --ntasks-per-node=1 --output=${{ secrets.SSH_WORK_DIR }}/logs/${{ github.sha }}/out.log --error=${{ secrets.SSH_WORK_DIR }}/logs/${{ github.sha}}/error.log slurm_testing_callback/regression_run_scripts/regtest_lite.sh --home_dir ${{ secrets.SSH_WORK_DIR }} --image ${{ env.DOCKER_TAG }} --sha ${{ github.sha }}
            else
              sbatch -N 1 -p RM-shared -t 00:05:00 --ntasks-per-node=1 --output=${{ secrets.SSH_WORK_DIR }}/logs/${{ github.sha }}/out.log --error=${{ secrets.SSH_WORK_DIR }}/logs/${{ github.sha}}/error.log slurm_testing_callback/regression_run_scripts/regtest_lite.sh --home_dir ${{ secrets.SSH_WORK_DIR }} --image ${{ env.DOCKER_TAG }} --sha ${{ github.sha }} --path-extra ${{ secrets.GH_CLI_BIN_PATH }}
            fi

      #- name: Correlating
      #  run: |
      #    echo "Correlating lite regression runs"
      #    echo "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"
      #    python3 reg-suite/main.py correlate --pipeline1 $GITHUB_WORKSPACE/output/default/HNU_1 --pipeline2 $GITHUB_WORKSPACE/lite/default/HNU_1--workspace $GITHUB_WORKSPACE

      - name: Cleanup SSH
        run: |
          rm -rf ~/.ssh

      #- uses: actions/upload-artifact@v3
      #  if: always()
      #  with:
      #    name: logs
      #    path: output/*/*/log/
