name: Run Regression Lite Test


on:
  #pull_request:
  #  types: [ready_for_review]
  workflow_call:
    secrets: 
      SSH_PRIVATE_KEY:
        required: true
      SSH_USER:
        required: true
      SSH_HOST:
        required: true
      SSH_WORK_DIR:
        required: true

jobs: 
  test:
    name: Regression Test - Lite
    runs-on: ubuntu-latest
    steps: 
      - name: Get C-PAC branch
        run: |
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
          if [[ ! $GITHUB_BRANCH == 'main' ]] && [[ ! $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=${GITHUB_BRANCH//\//_}
          elif [[ $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=nightly
          elif [[ $GITHUB_BRANCH == 'main' ]]
          then
            TAG=latest
          fi
          TAG=$TAG$VARIANT
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):$TAG >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Clone reg-suite
        run: |
          git clone https://github.com/FCP-INDI/reg-suite.git

      - name: Install SSH Keys
        run: |
          install -m 600 -D /dev/null $GITHUB_WORKSPACE/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $GITHUB_WORKSPACE/.ssh/id_rsa
          ssh-keyscan -H -t rsa ${{ secrets.SSH_HOST }} > ~$GITHUB_WORKSPACE/.ssh/known_hosts
        shell: bash
        env:
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            SSH_KNOWN_HOSTS: ${{secrets.SSH_HOSTS}}
            SSH_KEY_PATH: $GITHUB_WORKSPACE/.ssh/id_rsa

      - name: Connect and Run
        run: |
          ssh -i $GITHUB_WORKSPACE/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && touch ./test.txt && exit"

      - name: Cleanup SSH
        run: |
          rm -rf ~/.ssh
      #- name: Run Lite Regression Test
      #  if: github.event_name == 'push'
      #  run: |
      #    #if [ "${{ github.event_name }}" = "pull_request" ] && [ "${{ github.event.pull_request.state }}" = "open" ]; then
      #    echo "Running lite regression test"
      #    echo "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"
      #    python3 reg-suite/main.py run --lite --docker_tag ${{ env.DOCKER_TAG }} --workspace $GITHUB_WORKSPACE

      #- name: Configure AWS Credentials
      #  uses: aws-actions/configure-aws-credentials@v2
      #  with:
      #      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #      aws-region: us-east-1

      #- name: Download from S3
      #  run: |
      #    aws s3 cp s3://fcp-indi/resources/cpac/regression/outputs/v1.8.5/lite/ $GITHUB_WORKSPACE/lite/ --recursive

      #- name: Correlating
      #  run: |
      #    echo "Correlating lite regression runs"
      #    echo "(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧"
      #    python3 reg-suite/main.py correlate --pipeline1 $GITHUB_WORKSPACE/output/default/HNU_1 --pipeline2 $GITHUB_WORKSPACE/lite/default/HNU_1--workspace $GITHUB_WORKSPACE

      #- uses: actions/upload-artifact@v3
      #  if: always()
      #  with:
      #    name: logs
      #    path: output/*/*/log/
