name: Run participant smoke test

on:
  workflow_dispatch:
    inputs:
      participant:
        required: true
        description: participant label
      preconfig:
        required: true
        description: preconfig name

jobs:
  smoke_test:
    name: Run smoke test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - ''
          - lite
          - ABCD-HCP
          - fMRIPrep-LTS
    steps:
      - name: Set up check
        uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
          name: "Smoke test: ${{ matrix.variant }} ${{ github.event.inputs.preconfig }} preconfig, participants: ${{ github.event.inputs.participant }}"
          status: in_progress
      - name: Get C-PAC
        run: |
          if [[ "${{ matrix.variant }}" != "" ]]
          then
            VARIANT=-${{ matrix.variant }}
          fi
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
          if [[ ! $GITHUB_BRANCH == 'main' ]] && [[ ! $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=${GITHUB_BRANCH//\//_}
          elif [[ $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=nightly$VARIANT
          elif [[ $GITHUB_BRANCH == 'main' ]]
          then
            TAG=latest$VARIANT
          fi
          TAG=$TAG$VARIANT
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):$TAG >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Run default smoke test
        if: ${{ github.event.inputs.preconfig == 'default' }}
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group \
            -v $PWD:/outputs \
            ${{ env.DOCKER_TAG }} \
            /outputs /outputs test_config \
            --data_config_file /code/CPAC/resources/configs/test_configs/data-test_human.yml \
            --participant_label ${{ github.event.inputs.participant }} \
            --n_cpus 1
      - name: Run ${{ github.event.inputs.preconfig }} smoke test
        if: ${{ github.event.inputs.preconfig != 'default' }}
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group \
            -v $PWD:/outputs \
            ${{ env.DOCKER_TAG }} \
            /outputs /outputs test_config \
            --data_config_file /code/CPAC/resources/configs/test_configs/data-test_human.yml \
            --participant_label ${{ github.event.inputs.participant }} \
            --preconfig ${{ github.event.inputs.preconfig }} \
            --n_cpus 1
      - uses: LouisBrunner/checks-action@v1.1.1
        if: always()
        with:
          token: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
          check_id: "Smoke test: ${{ matrix.variant }} ${{ github.event.inputs.preconfig }} preconfig, participants: ${{ github.event.inputs.participant }}"
          conclusion: ${{ job.status }}
