name: "Smoke test: participant preconfigurations"
# Runs on pull request after build

on:
  workflow_dispatch:
    inputs:
      dataset:
        description: Dataset to test
        required: true


jobs:
  test_human_ADHD200:
    name: Test preconfigs on ADHD200 human participants
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dataset }} == "ADHD200"
    strategy:
      matrix:
        preconfig:
          - default
          - abcd-options
          - anat-only
          - benchmark-ANTS
          - benchmark-FNIRT
          - blank
          - ccs-options
          - fmriprep-options
          - fx-options
          - ndmg
          - preproc
          - rbc-options
          - regtest-1
          - regtest-2
          - regtest-3
          - regtest-4
        participant:
          - '1019436'
          - '2014113'
          - '3154996'
          - '3699991'
          - '3884955'
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run participant-level smoke tests
        run: gh workflow run smoke_test_participant.yml --ref ${GITHUB_REF_NAME} -f participant="${{ matrix.participant }}" -f preconfig="${{ matrix.preconfig }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
  test_human_HBN:
    name: Test preconfigs on HBN human participants
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dataset }} == "HBN"
    strategy:
      matrix:
        preconfig:
          - default
          - abcd-options
          - anat-only
          - benchmark-ANTS
          - benchmark-FNIRT
          - blank
          - ccs-options
          - fmriprep-options
          - fx-options
          - ndmg
          - preproc
          - rbc-options
          - regtest-1
          - regtest-2
          - regtest-3
          - regtest-4
        participant:
          - NDARAA504CRN
          - NDARAA947ZG5
          - NDARAB348EWR
          - NDARAB458VK9
          - NDARAD481FXF
          - NDARAV894XWD
          - NDARCA186WGH
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run participant-level smoke tests
        run: gh workflow run smoke_test_participant.yml --ref ${GITHUB_REF_NAME} -f participant="${{ matrix.participant }}" -f preconfig="${{ matrix.preconfig }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
  test_human_CORR:
    name: Test preconfigs on CORR human participants
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.dataset }} == "CORR"
    strategy:
      matrix:
        preconfig:
          - default
          - abcd-options
          - anat-only
          - benchmark-ANTS
          - benchmark-FNIRT
          - blank
          - ccs-options
          - fmriprep-options
          - fx-options
          - ndmg
          - preproc
          - rbc-options
          - regtest-1
          - regtest-2
          - regtest-3
          - regtest-4
        participant:
          - '0025428'
          - '0025429'
          - '0025448'
          - '0025452'
          - '0025453'
    steps:
      - name: Check out C-PAC
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Run participant-level smoke tests
        run: gh workflow run smoke_test_participant.yml --ref ${GITHUB_REF_NAME} -f participant="${{ matrix.participant }}" -f preconfig="${{ matrix.preconfig }}"
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}

  # test_nhp_configs:
  #   name: Smoke test nonhuman primate preconfigs
  #   strategy:
  #     matrix:
  #       variant:
  #         - ''
  #         - lite
  #         - ABCD-HCP
  #         - fMRIPrep-LTS
  #       preconfig:
  #         - monkey
  #         - monkey-ABCD
  #         - nhp-macaque
  #   runs-on: ubuntu-latest
  #   steps:
  # test_rodent_configs:
  #   name: Smoke test rodent preconfigs
  #   strategy:
  #     matrix:
  #       variant:
  #         - ''
  #         - lite
  #         - ABCD-HCP
  #         - fMRIPrep-LTS
  #       preconfig:
  #         - rodent
  #   runs-on: ubuntu-latest
  #   steps: