name: Run participant smoke test

on:
  workflow_dispatch:

jobs:
  smoke_test:
    name: Run human participant smoke tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        preconfig:
          - default
          - abcd-options
          - anat-only
          - benchmark-ANTS
          - benchmark-FNIRT
          - blank
          - ccs-options
          - fmriprep-options
          - fx-options
          - ndmg
          - preproc
          # - rbc-options
          - regtest-1
          - regtest-2
          - regtest-3
          - regtest-4
        variant:
          - ''
          - lite
          - ABCD-HCP
          - fMRIPrep-LTS
        participant:
          - 1019436 2014113 3154996 3699991 3884955  # ADHD200
          - NDARAA504CRN NDARAA947ZG5 NDARAB348EWR NDARAB458VK9 NDARAD481FXF NDARAV894XWD NDARCA186WGH  # HBN
          - 0025428 0025429 0025448 0025452 0025453  # CORR
    steps:
      - name: Set up check
        uses: Sibz/github-status-action@v1.1.6
        if: ${{ matrix.variant }} != ''
        with:
          authToken: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
          context: "Smoke test (${{ matrix.variant }}): ${{ matrix.preconfig }} preconfig, participants: ${{ matrix.participant }}"
          state: pending
      - name: Get C-PAC
        run: |
          if [[ "${{ matrix.variant }}" != "" ]]
          then
            VARIANT=-${{ matrix.variant }}
          fi
          GITHUB_BRANCH=$(echo ${GITHUB_REF} | cut -d '/' -f 3-)
          if [[ ! $GITHUB_BRANCH == 'main' ]] && [[ ! $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=${GITHUB_BRANCH//\//_}
          elif [[ $GITHUB_BRANCH == 'develop' ]]
          then
            TAG=nightly$VARIANT
          elif [[ $GITHUB_BRANCH == 'main' ]]
          then
            TAG=latest$VARIANT
          fi
          TAG=$TAG$VARIANT
          echo DOCKER_TAG=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]'):$TAG >> $GITHUB_ENV
          cat $GITHUB_ENV
      - name: Run default smoke test
        if: ${{ matrix.preconfig == 'default' }}
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group \
            -v $PWD:/outputs \
            ${{ env.DOCKER_TAG }} \
            /outputs /outputs test_config \
            --data_config_file /code/CPAC/resources/configs/test_configs/data-test_human.yml \
            --participant_label ${{ matrix.participant }} \
            --n_cpus 1
      - name: Run ${{ matrix.preconfig }} smoke test
        if: ${{ matrix.preconfig != 'default' }}
        run: |
          docker run --rm \
            --user $(id -u):$(id -g) -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group \
            -v $PWD:/outputs \
            ${{ env.DOCKER_TAG }} \
            /outputs /outputs test_config \
            --data_config_file /code/CPAC/resources/configs/test_configs/data-test_human.yml \
            --participant_label ${{ matrix.participant }} \
            --preconfig ${{ matrix.preconfig }} \
            --n_cpus 1
      - name: Finish check
        uses: Sibz/github-status-action@v1.1.6
        if: always()
        with:
          authToken: ${{ secrets.ACTIONS_WORKFLOW_TOKEN }}
          context: "Smoke test: ${{ matrix.variant }} ${{ matrix.preconfig }} preconfig, participants: ${{ matrix.participant }}"
          state: ${{ job.status }}
